const actionTypes = {
    DATA_REQUESTED: 'DATA_REQUESTED',
    DATA_LOADED: 'DATA_LOADED',
    API_ERROR: 'API_ERROR',
    RESET_DATA: 'RESET_DATA',
    SET_FILTER: 'SET_FILTER',
    SET_POKEMON: 'SET_POKEMON',
    FETCH_DESCRIPTION: 'FETCH_DESCRIPTION',
    FETCHED_DESCRIPTION: 'FETCHED_DESCRIPTION',
    LOAD_MOVES: 'LOAD_MOVES',
    MOVE_REQUEST: 'MOVE_REQUEST',
    MOVE_LOADING: 'LOADING_MOVE',
    MOVE_LOADED: 'MOVE_LOADED'
};

export default actionTypes;